fn main() {
    const COMMANDS: &[&str] = &[
        "bootstrap",
        "subscribe_stream",
        "unsubscribe_stream",
        "get_history",
        "get_session_events",
        "set_overlay_mode",
        "open_dashboard",
        "open_session",
        "acknowledge_attention",
        "get_settings",
        "list_displays",
        "update_settings",
        "purge_history",
        "set_startup_enabled",
        "set_global_shortcut",
        "integration_health",
        "preview_connector_change",
        "apply_connector_change",
        "remove_connector",
        "repair_connector",
        "rollback_connector",
        "detect_connectors",
        "connector_health",
        "list_connector_backups",
        "list_pending_decisions",
        "submit_decision",
        "get_sound_themes",
        "preview_sound_routing",
        "play_sound_event",
        "import_sound_pack",
        "list_remote_hosts",
        "upsert_remote_host",
        "remove_remote_host",
        "get_remote_backend_status",
        "preview_remote_deploy",
        "execute_remote_deploy",
        "start_remote_relay",
        "stop_remote_relay",
        "get_remote_connection_status",
    ];
    let attributes = tauri_build::Attributes::new()
        .app_manifest(tauri_build::AppManifest::new().commands(COMMANDS));
    tauri_build::try_build(attributes).expect("failed to generate Tauri command permissions");
}
