// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Observation paths supported by an adapter (Sol capability matrix).
 */
export type AdapterObservationPaths = { lifecycleEvents: boolean, toolEvents: boolean, attentionEvents: boolean, };
