// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSource } from "./AgentSource";
import type { AttentionCapability } from "./AttentionCapability";
import type { AttributionQuality } from "./AttributionQuality";

/**
 * Capability flags advertised by an adapter integration.
 */
export type AdapterCapabilities = { source: AgentSource, events: boolean, attention: AttentionCapability, decisionResponse: boolean, contextOpen: boolean, processAttribution: AttributionQuality, };
