// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSource } from "./AgentSource";
import type { AttentionCapability } from "./AttentionCapability";
import type { AttributionQuality } from "./AttributionQuality";
import type { ContextOpenTier } from "./ContextOpenTier";

/**
 * Capability flags advertised by an adapter integration.
 */
export type AdapterCapabilities = { source: AgentSource, events: boolean, attention: AttentionCapability, decisionResponse: boolean, contextOpen: boolean, processAttribution: AttributionQuality, contextOpenTier: ContextOpenTier, observeLifecycle: boolean, observeTools: boolean, respondDecisions: boolean, respondQuestions: boolean, failOpenHooks: boolean, requiresExternalTrust: boolean, };
