// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextOpenTier } from "./ContextOpenTier";

/**
 * Response paths supported by an adapter (Sol capability matrix).
 */
export type AdapterResponsePaths = { decisions: boolean, questions: boolean, contextOpenTier: ContextOpenTier, };
