// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricQuality } from "./MetricQuality";

/**
 * Deduplicated resource totals across all attributed agent process trees.
 */
export type AgentAggregate = { atMs: number, cpuCorePercent: number, cpuHostPercent: number, rssBytes: number, runtimeMs: number, processCount: number, readBytesPerSec: number, writeBytesPerSec: number, quality: MetricQuality, activeSessions: number, attentionSessions: number, };
