// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies which agent runtime produced a session.
 */
export type AgentSource = "cursor" | "claudeCode" | "codex" | "generic" | "unknown";
