// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSource } from "./AgentSource";
import type { AttentionKind } from "./AttentionKind";
import type { MetricSample } from "./MetricSample";
import type { ProcessIdentity } from "./ProcessIdentity";
import type { SessionStatus } from "./SessionStatus";

/**
 * Canonical agent session record exchanged between host and UI.
 */
export type AgentSession = { 
/**
 * Stable session id (bounded by [`crate::MAX_SESSION_ID_LEN`]).
 */
id: string, source: AgentSource, 
/**
 * Source-owned session identifier, namespaced by `source`.
 */
externalSessionId: string, 
/**
 * Privacy-preserving display label.
 */
label: string, workspaceLabel?: string, status: SessionStatus, attention: AttentionKind, startedAtMs: number, lastEventAtMs: number, endedAtMs?: number, processRoot?: ProcessIdentity, latestMetric?: MetricSample, };
