// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterCapabilities } from "./AdapterCapabilities";
import type { AgentAggregate } from "./AgentAggregate";
import type { AgentSession } from "./AgentSession";
import type { HostMetricSample } from "./HostMetricSample";
import type { PublicSettings } from "./PublicSettings";

import type { ResourceAlert } from "./ResourceAlert";

/**
 * Point-in-time host snapshot delivered to renderers.
 */
export type AppSnapshot = { protocolVersion: number, capturedAtMs: number, host?: HostMetricSample, aggregate?: AgentAggregate, sessions: Array<AgentSession>, settings: PublicSettings, adapters: Array<AdapterCapabilities>, resourceAlerts: Array<ResourceAlert>, };
