// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of user attention a session currently requires.
 */
export type AttentionKind = "none" | "approval" | "question" | "permission" | "error";
