// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fidelity of attention reporting offered by an adapter.
 */
export type AttentionCapability = "full" | "partial" | "none";
