// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Confidence in process/session attribution.
 */
export type AttributionQuality = "exact" | "shared" | "heuristic" | "unknown";
