// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSource } from "./AgentSource";
import type { BackupJournalOperation } from "./BackupJournalOperation";

/**
 * Journal entry for backup create/restore operations.
 */
export type BackupJournalEntry = { id: string, planId?: string, source: AgentSource, 
/**
 * Display-only target path label.
 */
displayPath: string, 
/**
 * Display-only backup path label.
 */
backupDisplayPath: string, contentSha256: string, appliedHash?: string, operation: BackupJournalOperation, recordedAtMs: number, };
