// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterCapabilities } from "./AdapterCapabilities";
import type { AgentSource } from "./AgentSource";
import type { ConnectorFileApplyResult } from "./ConnectorFileApplyResult";

/**
 * Apply result for a confirmed plan. Multi-file apply is per-file atomic with honest partial success.
 */
export type ConnectorApplyResult = { planId: string, source: AgentSource, fileResults: Array<ConnectorFileApplyResult>, capabilities: AdapterCapabilities, };
