// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectorHealthEntry } from "./ConnectorHealthEntry";

export type ConnectorHealthReport = { checkedAtMs: number, adapters: Array<ConnectorHealthEntry>, };
