// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterCapabilities } from "./AdapterCapabilities";
import type { AgentSource } from "./AgentSource";
import type { ConnectorUserStatus } from "./ConnectorUserStatus";
import type { HealthProbeResult } from "./HealthProbeResult";

export type ConnectorHealthEntry = { source: AgentSource, status: ConnectorUserStatus, probes: Array<HealthProbeResult>, capabilities: AdapterCapabilities, detail?: string, };
