// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Deterministic user-facing connector status derived from probe results.
 */
export type ConnectorUserStatus = "notFound" | "notInstalled" | "actionNeeded" | "waitingFirstEvent" | "helperMissing" | "hooksMisconfigured" | "connected" | "driftDetected" | "error";
