// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectorErrorCode } from "./ConnectorErrorCode";
import type { ConnectorFileOutcome } from "./ConnectorFileOutcome";

export type ConnectorFileApplyResult = { displayPath: string, outcome: ConnectorFileOutcome, backupJournalId?: string, appliedHash?: string, errorCode?: ConnectorErrorCode, message?: string, };
