// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectorErrorCode } from "./ConnectorErrorCode";
import type { ConnectorFileApplyResult } from "./ConnectorFileApplyResult";

export type ConnectorApplyError = { code: ConnectorErrorCode, message: string, expectedSha256?: string, actualSha256?: string, partialResults?: Array<ConnectorFileApplyResult>, };
