// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSource } from "./AgentSource";
import type { ConnectorFileApplyResult } from "./ConnectorFileApplyResult";
import type { ConnectorScope } from "./ConnectorScope";

/**
 * Connector apply/remove journal entry for rollback and audit.
 */
export type ConnectorJournalEntry = { id: string, planId: string, source: AgentSource, scope: ConnectorScope, startedAtMs: number, completedAtMs?: number, fileResults: Array<ConnectorFileApplyResult>, rollbackAvailable: boolean, };
