// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSource } from "./AgentSource";
import type { ConnectorFilePreview } from "./ConnectorFilePreview";
import type { ConnectorScope } from "./ConnectorScope";
import type { ExternalTrustAction } from "./ExternalTrustAction";

/**
 * Short-lived plan returned by preview; apply accepts only `plan_id`.
 */
export type ConnectorPlanPreview = { planId: string, source: AgentSource, scope: ConnectorScope, expiresAtMs: number, summary: string, files: Array<ConnectorFilePreview>, externalTrustActions: Array<ExternalTrustAction>, 
/**
 * Display-only hint for where a backup will be written; not an apply input.
 */
backupDisplayHint?: string, };
