// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectorErrorCode = "planExpired" | "planNotFound" | "fileChangedSincePreview" | "lockContention" | "pathEscapesScope" | "partialApplyFailure" | "activeConnectorBlocked" | "rollbackHashMismatch" | "internalError";
