// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-file preview entry. `display_path` is redacted for UI; canonical identity is backend-only.
 */
export type ConnectorFilePreview = { 
/**
 * Display-only redacted path label for diff review UI.
 */
displayPath: string, baselineSha256: string, 
/**
 * Unified diff text for display; may be truncated by transport limits.
 */
diffText: string, 
/**
 * Hook or config entries from other tools preserved by merge.
 */
foreignEntriesPreserved: Array<string>, isNewFile: boolean, };
