// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome for a single file within a multi-file apply.
 */
export type ConnectorFileOutcome = "applied" | "skipped" | "failed";
