// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Granularity of context-open support advertised by an adapter.
 */
export type ContextOpenTier = "none" | "appActivate" | "windowFocus" | "exactPane";
