// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSource } from "./AgentSource";
import type { DecisionKind } from "./DecisionKind";

/**
 * Decision prompt surfaced to UI layers. Ephemeral vendor payload stays backend-only.
 */
export type DecisionRequest = { id: string, sessionId: string, source: AgentSource, kind: DecisionKind, 
/**
 * Redacted summary safe for overlay/dashboard display.
 */
summary: string, 
/**
 * When false, UI must not render Allow/Deny/answer controls.
 */
hasActionablePayload: boolean, createdAtMs: number, expiresAtMs?: number, };
