// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionResponseAction } from "./DecisionResponseAction";

export type DecisionResponse = { "type": "action", action: DecisionResponseAction, } | { "type": "answer", text: string, };
