// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionDeliveryState } from "./DecisionDeliveryState";
import type { DecisionResponse } from "./DecisionResponse";

export type DecisionResponseRecord = { requestId: string, response: DecisionResponse, respondedAtMs: number, deliveryState: DecisionDeliveryState, deliveryDetail?: string, };
