// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Honest delivery lifecycle; never claim vendor ACK without evidence.
 */
export type DecisionDeliveryState = "pending" | "delivered" | "effectObserved" | "expired" | "failed";
