// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity assigned to a normalized session event.
 */
export type EventLevel = "debug" | "info" | "warning" | "error";
