// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * External trust steps the user must complete outside llm_notch (e.g. Codex `/hooks`).
 */
export type ExternalTrustActionKind = "codexHooksReview" | "other";
