// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalTrustActionKind } from "./ExternalTrustActionKind";

export type ExternalTrustAction = { kind: ExternalTrustActionKind, 
/**
 * User-facing instructions; never includes secrets or raw vendor payloads.
 */
instructions: string, };
