// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional machine-readable reason when a probe is not OK.
 */
export type HealthProbeFailureKind = "agentNotFound" | "notInstalled" | "trustRequired" | "helperUnavailable" | "helperPathMissing" | "hooksMisconfigured" | "noTraffic" | "configDrift" | "internalError";
