// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Independent health dimensions evaluated by the connector manager.
 */
export type HealthProbeAxis = "installation" | "trust" | "traffic" | "helper" | "process";
