// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome for a single probe axis.
 */
export type HealthProbeOutcome = "ok" | "warn" | "fail";
