// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthProbeAxis } from "./HealthProbeAxis";
import type { HealthProbeFailureKind } from "./HealthProbeFailureKind";
import type { HealthProbeOutcome } from "./HealthProbeOutcome";

/**
 * Result of evaluating one orthogonal probe axis.
 */
export type HealthProbeResult = { axis: HealthProbeAxis, outcome: HealthProbeOutcome, failureKind?: HealthProbeFailureKind, detail?: string, };
