// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * System-wide resource sample.
 */
export type HostMetricSample = { atMs: number, cpuHostPercent: number, usedMemoryBytes: number, totalMemoryBytes: number, visibleProcessCount: number, diskReadBytesPerSec: number, diskWriteBytesPerSec: number, };
