// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scope and reliability of process I/O counters.
 */
export type IoQuality = "disk" | "allIo" | "partial" | "unavailable";
