// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentAggregate } from "./AgentAggregate";
import type { HostMetricSample } from "./HostMetricSample";
import type { MetricSample } from "./MetricSample";

/**
 * One live metrics update delivered to renderer subscribers.
 */
export type MetricsFrame = { host: HostMetricSample, aggregate: AgentAggregate, agents: { [key in string]: MetricSample }, };
