// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricQuality } from "./MetricQuality";

/**
 * Resource sample for a single attributed session process tree.
 */
export type MetricSample = { atMs: number, 
/**
 * 100% equals one logical core and may exceed 100%.
 */
cpuCorePercent: number, 
/**
 * Host-normalized CPU percentage in the range 0..=100.
 */
cpuHostPercent: number, rssBytes: number, runtimeMs: number, processCount: number, readBytesPerSec: number, writeBytesPerSec: number, quality: MetricQuality, };
