// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Availability of a sampled metric family.
 */
export type MetricAvailability = "available" | "warmingUp" | "unavailable";
