// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttributionQuality } from "./AttributionQuality";
import type { IoQuality } from "./IoQuality";
import type { MetricAvailability } from "./MetricAvailability";

/**
 * Quality metadata carried beside every per-agent and aggregate sample.
 */
export type MetricQuality = { attribution: AttributionQuality, cpu: MetricAvailability, io: IoQuality, 
/**
 * Bounded diagnostic explanation when a metric family is degraded.
 */
reason?: string, };
