// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MigrationLane } from "./MigrationLane";

export type MigrationRecord = { lane: MigrationLane, version: number, appliedAtMs: number, checksum?: string, };
