// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MigrationRecord } from "./MigrationRecord";

export type MigrationRegistry = { registryVersion: number, records: Array<MigrationRecord>, };
