// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lane identifiers for future migrations. Values are stable wire numbers.
 */
export type MigrationLane = "connectors" | "decisions" | "metrics" | "platform";
