// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable identity for an OS process associated with a session.
 */
export type ProcessIdentity = { 
/**
 * Operating-system process identifier.
 */
pid: number, 
/**
 * Process creation time; paired with PID to survive PID reuse.
 */
startedAtMs: number, };
