// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SoundRouting } from "./SoundRouting";

/**
 * User-visible settings safe to expose to overlay and dashboard surfaces.
 */
export type PublicSettings = { overlayEnabled: boolean, autostartEnabled: boolean, reducedMotion: boolean, samplingIntervalMs: number, selectedDisplay?: string, showOverFullscreen: boolean, historyRetentionHours: number, 
/**
 * Optional alert sound; off by default and never activates windows.
 */
alertSoundEnabled: boolean, 
/**
 * Installed theme id; falls back to `builtin.8-bit` when unset.
 */
selectedSoundThemeId?: string, 
/**
 * Per-event and quiet-hours routing applied to native playback.
 */
soundRouting: SoundRouting, };
