// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-visible settings safe to expose to overlay and dashboard surfaces.
 */
export type PublicSettings = { overlayEnabled: boolean, autostartEnabled: boolean, reducedMotion: boolean, samplingIntervalMs: number, selectedDisplay?: string, showOverFullscreen: boolean, historyRetentionHours: number, };
