// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Purge scope for privacy controls. Backups are kept by default; `include_backups`
 * is an explicit opt-in. "Delete all data" must handle active connectors first.
 */
export type PurgeScope = { history: boolean, sessionEvents: boolean, connectorJournal: boolean, 
/**
 * Explicit opt-in to delete connector backup files.
 */
includeBackups: boolean, };
