// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PurgeResult = { historyRowsRemoved: number, eventsRemoved: number, backupsRemoved: number, activeConnectorsDisconnected: number, };
