// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResourceAlertKind = "cpuWarn" | "cpuCritical" | "memoryHigh";

/**
 * Non-attention host resource alert surfaced to overlay and tray (never focus-steals).
 */
export type ResourceAlert = { kind: ResourceAlertKind, message: string, sessionId?: string, raisedAtMs: number, };
