// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kind of timeline event within a session.
 */
export type SessionEventKind = "lifecycle" | "tool" | "attention" | "status";
