// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventLevel } from "./EventLevel";
import type { SessionEventKind } from "./SessionEventKind";

/**
 * Timeline event belonging to a session.
 */
export type SessionEvent = { id: string, sessionId: string, sequence: number, occurredAtMs: number, kind: SessionEventKind, level: EventLevel, 
/**
 * Redacted event summary (bounded by [`crate::MAX_EVENT_SUMMARY_LEN`]).
 */
summary: string, toolName?: string, };
