// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * High-level lifecycle state for an agent session.
 */
export type SessionStatus = "starting" | "running" | "waiting" | "paused" | "completed" | "failed" | "stale";
