// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sound event kinds mapped by installed themes (never invent new variants here).
 */
export type SoundEvent = "approval" | "question" | "completed" | "failed" | "notification";
