// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuietHours } from "./QuietHours";
import type { SoundEvent } from "./SoundEvent";

export type SoundRouting = { enabled: boolean, volume: number, quietHours?: QuietHours, eventVolume: { [key in SoundEvent]?: number }, agentVolume: { [key in string]: number }, };
