// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterCapabilities } from "./AdapterCapabilities";
import type { AgentSession } from "./AgentSession";
import type { AppSnapshot } from "./AppSnapshot";
import type { MetricsFrame } from "./MetricsFrame";
import type { PublicSettings } from "./PublicSettings";
import type { SessionEvent } from "./SessionEvent";

/**
 * Individual stream payload variants.
 */
export type StreamPayload = { "type": "snapshot", snapshot: AppSnapshot, } | { "type": "sessionUpsert", session: AgentSession, } | { "type": "sessionRemove", sessionId: string, } | { "type": "sessionEvent", event: SessionEvent, } | { "type": "metrics", metrics: MetricsFrame, } | { "type": "settingsChanged", settings: PublicSettings, } | { "type": "integrationChanged", integration: AdapterCapabilities, } | { "type": "heartbeat" } | { "type": "resyncRequired", 
/**
 * Bounded explanation suitable for diagnostics, not display of secrets.
 */
reason: string, };
