// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StreamPayload } from "./StreamPayload";

/**
 * Framed stream envelope with monotonic sequencing.
 */
export type StreamFrame = { sequence: number, emittedAtMs: number, payload: StreamPayload, };
