// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Verified terminal navigation identifiers supplied by a collector or OS bridge.
 *
 * Callers must not populate these values by parsing mutable window titles.
 */
export type VerifiedTerminalContext = { terminalSessionId?: string, tabId?: string, paneId?: string, windowHandle?: number, };
